### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by iangilman** [christianboyle/eo1-workaround#1]
Thank you for putting these instructions together! 

I have a question: I assume if the device loses power, I'll have to plug the hub back in and restart Firefox? Is there a way to set it up so it'll automatically start Firefox on restart? I ask because my EO1 is unfortunately on a flaky circuit that loses power from time to time.

**Comment by christianboyle** [comment]
> Thank you for putting these instructions together!

My pleasure!

> I assume if the device loses power, I'll have to plug the hub back in and restart Firefox?

That's correct and I'm actually not sure of a way to fix that issue.

Have you looked at https://github.com/spalt/EO1/? It's probably a better option if you need the reboot-to-running-app functionality (it works, I just tested it).

**Comment by iangilman** [comment]
@christianboyle I haven't tried splat's app yet. I'm actually still just trying to get into the device! I've posted my current conundrum here: https://www.reddit.com/r/electricobjects/comments/188w596/eo1_how_to_open_web_browser_when_windows_b_doesnt/

Anyway, I really just want a web browser, since the content I want to display is already nicely packaged up on a website, so it seems splat's app isn't necessarily what I need.

Thank you again for the help!

**Comment by christianboyle** [comment]
@iangilman What keyboard are you using?

**Comment by wasauce** [comment]
@christianboyle what keyboards work? I tried a apple keyboard and didn't get it to work, and then I tried a Advantage2 from Kinesis -- also didn't work. I am not OP but I have the same issue. 

Thank you!

**Comment by christianboyle** [comment]
@wasauce @iangilman 

Those won't work, from what I know. I initially tried a wired and wireless Apple keyboard without any luck. It was only once I switched to a wired Logitech G710+ with a real Windows key that I got Windows + B to work.

**Comment by iangilman** [comment]
I'm using an old USB Dell keyboard. It's got a Windows key which works just fine on my PC.

**Comment by wasauce** [comment]
> @wasauce @iangilman
> 
> Those won't work, from what I know. I initially tried a wired and wireless Apple keyboard without any luck. It was only once I switched to a wired Logitech G710+ with a real Windows key that I got Windows + B to work.

Thank you @christianboyle I will try to find an appropriate keyboard.

**Comment by christianboyle** [comment]
@iangilman 

> I'm using an old USB Dell keyboard. It's got a Windows key which works just fine on my PC.

Yea, I'd think that would work. But the fact that Alt + Tab works makes me think that the Windows key isn't working as expected. When using that keyboard on a PC does the Windows key trigger the Taskbar Search to show?

**Comment by iangilman** [comment]
Are you saying Alt + Tab shouldn't work on the EO1? I'm not familiar with this system, so I don't know what to expect.

And yes, when I use the Windows key on my PC, it brings up the taskbar search.

**Comment by christianboyle** [comment]
@iangilman Sorry, `Alt + Tab` should work. I was just trying to reduce the number of potential issues.

Do any of the other standard shortcuts work?

- `Win + a` should bring up the calculator (`esc` to close)
- `Win + c` should bring up contacts (`esc` to close)

**Comment by iangilman** [comment]
Thank you for helping me debug this!

Neither of those shortcuts work either.

I'll try to get my hands on some other keyboards and/or OTG connectors.

Please let me know if you have any other thoughts!

**Comment by iangilman** [comment]
OK, I tried another keyboard (borrowed from a neighbor) and this one worked! I now have my webpage running in Firefox. Thank you again for all the help! ❤️

**Comment by christianboyle** [comment]
That's great news!

**Comment by wasauce** [comment]
I tried another keyboard - https://www.amazon.com/dp/B00ZYLMQH0?psc=1&ref=ppx_yo2ov_dt_b_product_details and it worked great.

Thank you for your help!

**Comment by christianboyle** [comment]
@wasauce Glad to hear it, thanks for the update!
